project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"

lang: ko-KR
date-format: "YYYY년 MM월 DD일"


website:
  title: "한국 R 사용자회"
  site-url: https://r2bit.com
  image: "fig/koRea_logo.png"
  google-analytics: "UA-229551680-1"
  page-footer:
    left: |
      사업자 등록번호: 735-82-003300 <br>
      대표: 형환희, 전자우편: <a href="mailto:admin@r2bit.com">admin@r2bit.com</a> <br>
      주소: 서울특별시 서초구 법원로3길 15, 4층 <br>
      &copy; 2024 BitStat. All rights reserved.
    right: |
      본 웹사이트는 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.
    
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "Home"
      - text: "(공개)패키지"
        href: packages.qmd
      - text: "(전자)책"
        href: book.qmd
      - text: "데이터"
        href: data.qmd
      - href: blog.qmd     
        text: "Blog"
      - text: "워크샵/발표자료"
        menu:
          - href: https://www.sharingkorea.net/gboard/
            text: "나눔국민운동본부"
          - href: https://r2bit.com/sen
            text: "서울교육청 - 혁신교육"            
          - href: https://choonghyunryu.github.io/workshop_lecture/
            text: "HCI 2024 (준비중)"
          - text: "----------------"
          - text: "챗GPT 발표자료"
            href: https://r2bit.com/bitSlide/
          - text: "**챗GPT**"
            href: https://r2bit.com/chatGPT/

      - text: "관련정보"
        menu:
          - text: "한국 R 컨퍼런스"
            href: https://use-r.kr/
          - text: "서울 R Meetup"
            href: https://www.meetup.com/seoul-r-meetup
          - text: "서울 R Meetup Archive"
            href: https://tidyverse-korea.github.io/seoul-R/
          - text: "----------------"
          - text: "글로벌 R Meetup"
            href: https://r2bit.com/seoul-r/
          - text: "쿼토(Quarto)"
            href: https://quarto.org/
          - text: "경진대회"
            href: contest.qmd
          - text: "----------------"
          - text: "소프트웨어 카펜트리"
            href: swc.qmd
          - text: "자기주도학습"
            href: learnr.qmd

    right: 
      - icon: discord
        href: https://discord.gg/2etGFvfk
      - icon: github
        href: https://github.com/bit2r
      - icon: facebook
        href: https://www.facebook.com/groups/tidyverse
      - icon: youtube
        href: https://www.youtube.com/channel/UCW-epmIvjBEhhVXw_F0Nqbw
        
  sidebar: 
    style: docked
    contents: 
      - section: "공익법인"
        contents:
          - text: "한국 R 사용자회"
            href: about.qmd
          - text: "행동강령(CoC)"
            href: coc.qmd
          - text: "후원 참여 및 기부 안내"
            href: donation.qmd            
          - text: "기부금 모금/활용실적"
            href: records.qmd
          - text: "과학기술정보통신부"
            href: https://www.msit.go.kr/
                
format:
  html:
    theme: 
      - litera
      - css/quarto.scss
    toc: true

filters:
  - lightbox
  - parse-latex
lightbox: auto

    
execute:
  freeze: false
