---
title: "콘텐츠"
description: |
  통계 대중화와 불평등 해소를 위해 전세계적으로 검증된 콘텐츠를 한국 알 사용자회에서 선별하여 크리에이티브 커먼즈 라이선스에 준용하여 번역 및 우리나라 상황을 반영하여 콘텐츠를 추가하였습니다. 디지털 콘텐츠도 재현성과 추적성이 강조되는 세계적인 현상을 감안하여 소프트웨어 개발 방법론을 적극 채용하여 지속적인 업그레이드와 개발이 이뤄지고 있습니다. 
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    css: "strapless.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r card-groups}
library(bs4cards)
library(tidyverse)

book_list <- list(
  tibble(
    title = "데이터 과학 프로그래밍",
    image = "fig/favicon_book_programming.png",
    text = "데이터 과학자로 성장하기 위한 프로그래밍 개념",
    link = "https://r2bit.com/book_programming/",
    footer = "2022-06-17"
  ),
  tibble(
    title = "데이터 시각화",
    image = "fig/favicon_book_viz.png",
    text = "데이터 시각화에 대한 개념과 실무",
    link = "https://r2bit.com/book_viz/",
    footer = "2022-06-03"
  ),
  tibble(
    title = "데이터 과학 기본기",
    image = "fig/favicon_book_basic.png",
    text = "데이터 과학을 지탱하는 기본기",
    link = "https://r2bit.com/book_analytics/",
    footer = "2022-06-04"
  ),
  tibble(
    title = "오픈 통계 패키지",
    image = "fig/favicon_book_rcmdr.png",
    text = "설치형 오픈 통계 패키지 - Rcmdr",
    link = "https://r2bit.com/Rcmdr/",
    footer = "2022-06-05"
  ),
  tibble(
    title = "데이터 과학 언플러그드",
    image = "fig/favicon_book_unplugged.png",
    text = "종이와 연필로 데이터 과학 개념 설명",
    link = "https://r2bit.com/book_unplugged/",
    footer = "2022-06-10"
  ),
  tibble(
    title = "문서 콘텐츠 제작 실무",
    image = "fig/favicon_book_document.png",
    text = "집필중",
    link = "",
    footer = "2022-07-XX"
  )  
)



book_tbl <- book_list %>% 
  enframe() %>% 
  unnest(value)

book_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )

```