---
title: "(전자)책"
description: |
  통계 대중화와 사회적 불평등 해소를 목표로 한국 R 사용자회는 전세계적으로 검증된 콘텐츠를 선별하고 크리에이티브 커먼즈 라이선스를 준용하여 한국어로 번역하는 것을 넘어, 국내 상황을 고려하여 챗GPT 연속간행물을 발간하고 있습니다. 이렇게 저작된 디지털 콘텐츠는 재현성과 추적성이 중요한 현대의 데이터 환경을 반영하고 있을 뿐만 아니라 체계적인 소프트웨어 개발 방법론을 적극 채용하고 있습니다. 지속적인 업그레이드와 개발을 통해 사용자에게 신뢰성과 지속성을 약속합니다. 공개 전자책은 이러한 철학과 방법론 아래, 누구나 자유롭게 접근할 수 있는 지식의 저장소로서의 역할을 충실히 하고 있습니다.
format:
  html:
    css: "strapless.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment = "#>", 
                      digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

## 출판 도서

```{r publish-groups}
#| echo: false

library(bs4cards)
library(tidyverse)

kyobo_list <- list(
  tibble(
    title = "챗GPT 유닉스 쉘",
    image = "fig/챗GPT_유닉스쉘.jpg",
    text = "<챗GPT 유닉스 쉘>은 생산성 자동화 도구를 다루고 있습니다.",
    link = "https://r2bit.com/gpt-shell/",
    footer = "2023-08-15"
  ),
  tibble(
    title = "챗GPT SQL",
    image = "fig/sql_cover.jpg",
    text = "<챗GPT SQL>은 SQL을 넘어 챗GPT와 떠나는 데이터 과학 여정을 담고 있습니다.",
    link = "https://r2bit.com/gpt-sql",
    footer = "2024-02-17"
  ),
  tibble(
    title = "챗GPT 쿼토",
    image = "fig/cover_quarto.jpg",
    text = "인공지능 시대 과학기술 저작 도구를 다루고 있습니다",
    link = "https://r2bit.com/gpt-quarto/",
    footer = "2024-03-01"
  ),
  tibble(
    title = "챗GPT 데이터 디지털 글쓰기",
    image = "fig/챗GPT_템플릿.png",
    text = "출간예정",
    link = "https://github.com/bit2r/gpt-writing",
    footer = "2023-11-15"
  ),
  tibble(
    title = "챗GPT 확률통계",
    image = "fig/챗GPT_템플릿.png",
    text = "출간예정",
    link = "https://github.com/bit2r/gpt-stat",
    footer = "2023-12-15"
  ),
  tibble(
    title = "챗GPT 프로그래밍",
    image = "fig/챗GPT_템플릿.png",
    text = "출간예정",
    link = "https://github.com/bit2r/gpt-programming",
    footer = "2024-01-15"
  )  
)

kyobo_tbl <- kyobo_list %>% 
  enframe() %>% 
  unnest(value)

kyobo_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )

```

<br>

- "챗GPT 유닉스 쉘: 데이터 과학 자동화 도구"
  - 뉴스기사: [챗GPT가 던진 새 가능성, 데이터 과학 분야 통해 미리 살펴보기](https://omn.kr/25f0i)

## 오픈 전자책

```{r card-groups}
#| echo: false

library(bs4cards)
library(tidyverse)

book_list <- list(
  tibble(
    title = "데이터 과학 프로그래밍",
    image = "fig/favicon_book_programming.png",
    text = "데이터 과학자로 성장하기 위한 프로그래밍 개념",
    link = "https://r2bit.com/book_programming/",
    footer = "2022-06-17"
  ),
  tibble(
    title = "데이터 시각화",
    image = "fig/favicon_book_viz.png",
    text = "데이터 시각화에 대한 개념과 실무",
    link = "https://r2bit.com/book_viz/",
    footer = "2022-06-03"
  ),
  tibble(
    title = "데이터 과학 기본기",
    image = "fig/favicon_book_basic.png",
    text = "데이터 과학을 지탱하는 기본기",
    link = "https://r2bit.com/book_analytics/",
    footer = "2022-06-04"
  ),
  tibble(
    title = "오픈 통계 패키지",
    image = "fig/favicon_book_rcmdr.png",
    text = "설치형 오픈 통계 패키지 - Rcmdr",
    link = "https://r2bit.com/Rcmdr/",
    footer = "2022-06-05"
  ),
  tibble(
    title = "데이터 과학 언플러그드",
    image = "fig/favicon_book_unplugged.png",
    text = "종이와 연필로 데이터 과학 개념 설명",
    link = "https://r2bit.com/book_unplugged/",
    footer = "2022-06-10"
  ),
  tibble(
    title = "문서 콘텐츠 제작 실무",
    image = "fig/favicon_book_document.png",
    text = "집필중",
    link = "",
    footer = "2022-XX-XX"
  ),
  tibble(
    title = "R 텍스트 마이닝",
    image = "fig/favicon_bitTA.png",
    text = "bitTA 패키지로 한글 텍스트 분석",
    link = "https://r2bit.com/book_tm/",
    footer = "2022-08-15"
  )  
)



book_tbl <- book_list %>% 
  enframe() %>% 
  unnest(value)

book_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )

```