---
title: "공개 패키지"
description: |
  외산 패키지에 의존하지 않고 R 개발자와 사용자의 작업 효율을 극대화하려는 목표 하에 다양한 분야별 핵심 패키지를 개발하고 있습니다. 데이터 과학 분야에서 CRAN에 등록된 `dlookr`과 `alookr` 패키지를 비롯하여, 오픈 통계 패키지 `bitStat`, 텍스트 자연어처리 `bitNLP`, 공간 데이터 `bitSpatial`, 보고서 자동화 `bitReport`, 출판 `bitPublish` 패키지가 특화된 기능을 제공하고 있다. 또한, 최근에 인기를 얻고 있는 생성형 AI 챗GPT를 손쉽게 활용할 수 있도록 `bitGPT` 패키지도 출시하하여 지속적 기여를 하고 있습니다.
format:
  html:
    css: "strapless.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE,
                      comment = "#>", 
                      digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```



```{r card-groups}
#| echo: false

library(bs4cards)
library(tidyverse)

package_list <- list(
  tibble(
    title = "bitReport",
    image = "fig/bitReport_logo.png",
    text = "휴먼 리소스 낭비를 없애는 보고서 자동화 도구",
    link = "https://github.com/bit2r/bitReport",
    footer = "2023-04-25"
  ),  
  tibble(
    title = "bitPublish",
    image = "fig/bitPublish_logo.png",
    text = "XeLaTeX 기반으로 한글 책을 PDF 파일로 조판",
    link = "https://github.com/bit2r/bitPublish",
    footer = "2023-04-25"
  ),  
  tibble(
    title = "bitGPT",
    image = "fig/bitGPT.png",
    text = "챗GPT를 보다 쉽게 사용할 수 있는, 그리고 한국어를 지원하는 bitGPT",
    link = "https://github.com/bit2r/bitGPT",
    footer = "2023-02-28"
  ),
  tibble(
    title = "bitNLP",
    image = "fig/bitNLP_logo.png",
    text = "텍스트 데이터를 탐색하고, 자연어 처리 및 형태소분석, 감성분석을 수행하는, 한글 텍스트 분석 도구모음",
    link = "https://github.com/bit2r/bitNLP",
    footer = "2022-12-18"
  ),
  tibble(
    title = "bitSpatial",
    image = "fig/bitSpatial_logo.png",
    text = "공간정보 데이터를 지탱하는 기본 패키지",
    link = "https://github.com/bit2r/bitSpatial",
    footer = "2023-01-23"
  ),
  tibble(
    title = "dlookr",
    image = "fig/dlookr_logo.png",
    text = "데이터셋의 품질 진단, 탐색적 데이터 분석(EDA) 및 데이터의 변환을 지원하는 데이터분석 도구",
    link = "https://cran.r-project.org/web/packages/dlookr/index.html",
    footer = "2018-04-27"
  ),
  tibble(
    title = "alookr",
    image = "fig/alookr_logo.png",
    text = "이진 분류 모델 개발의 전체 프로세스를 지원하는 데이터분석 도구",
    link = "https://cran.r-project.org/web/packages/alookr/index.html",
    footer = "2020-03-20"
  ),
  tibble(
    title = "bitStat",
    image = "fig/bitstat.png",
    text = "오픈 통계 패키지(BitStat)",
    link = "https://github.com/bit2r/BitStat",
    footer = "2021-09-18"
  )    
)



package_tbl <- package_list %>% 
  enframe() %>% 
  unnest(value)

package_tbl %>% 
  cards(
    title = title,
    text = text,
    link = link,
    image = image,
    footer = footer,
    layout = "label-left", 
    width = 3
  )

```
