project:
  type: website
  output-dir: ../docs/seoul-r

website:
  title: "서울R밋업"
  navbar:
    search: true
    left:
      - text: 소개
        href: index.Rmd
      - text: 2023년
        file: dashboard/meetup-2023.Rmd
      - text: 2022년
        file: dashboard/meetup-2022.Rmd
      - text: 2021년
        file: dashboard/meetup-2021.Rmd
      - text: 2020년
        file: dashboard/meetup-2020.Rmd
      - text: 2019년
        file: dashboard/meetup-2019.Rmd
      - text: 2018년
        file: dashboard/meetup-2018.Rmd
      - text: 연혁
        file: dashboard/history.Rmd
      - text: 행동강령
        file: dashboard/coc.Rmd

  body-header: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-59802572-23"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-59802572-23');
    </script>

  body-footer: |
    <div id="copyright">Copyright by R사용자회 <https://r2bit.com>. all rights reserved.</div>

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true

theme:
  light: cosmo
  dark: [cosmo, theme-dark.scss]
